#!/bin/bash
cd ~
# Install i3 gaps (ripped from https://github.com/Airblader/i3/wiki/Compiling-&-Installing)
echo "Installing i3gaps dependencies..."

sudo add-apt-repository ppa:aguignard/ppa
sudo apt-get update
sudo apt-get install libxcb-xrm-dev

sudo apt-get install libxcb1-dev libxcb-keysyms1-dev libpango1.0-dev libxcb-util0-dev libxcb-icccm4-dev libyajl-dev libstartup-notification0-dev libxcb-randr0-dev libev-dev libxcb-cursor-dev libxcb-xinerama0-dev libxcb-xkb-dev libxkbcommon-dev libxkbcommon-x11-dev autoconf libxcb-xrm-dev

echo "Installing i3gaps..."
# clone the repository
git clone https://www.github.com/Airblader/i3 i3-gaps
cd i3-gaps

# compile & install
autoreconf --force --install
rm -rf build/
mkdir -p build && cd build/

# Disabling sanitizers is important for release versions!
# The prefix and sysconfdir are, obviously, dependent on the distribution.
../configure --prefix=/usr --sysconfdir=/etc --disable-sanitizers
make
sudo make install

# Copy dotfiles
echo "Copying dotfiles..."
cp ~/dotfiles/dots/.config/i3/config ~/.config/i3/config
mkdir ~/.config/i3status
cp ~/dotfiles/dots/.config/i3status/config ~/.config/i3status/config

# Install google fonts
echo "Installing google fonts..."
cd ~
~/dotfiles/scripts/installers/googleFontsInstaller

# Install Microsoft fonts (ugh) | TODO Get working
# echo "Installing Microsoft fonts..."
# sudo apt-get install ttf-mscorefonts-installer

i3-msg restart

echo "Finished. All that's left is to manually copy the firefox dotfiles, if you want them."
