#!/bin/bash
cd ~
# Install base applications
echo "Installing i3, Vim, Firefox, compton, feh, scrot, i3lock, dunst, clang-format, figlet, w3m..."
sudo apt-get install i3 vim firefox compton feh scrot i3lock dunst clang-format figlet w3m

# Copy dotfiles
echo "Copying dotfiles..."
cp ~/dotfiles/dots/.vimrc ~/.vimrc
mkdir ~/.config/zathura
cp ~/dotfiles/dots/.config/zathura/zathurarc ~/.config/zathura/zathurarc
cp ~/dotfiles/dots/.config/compton.conf ~/.config/compton.conf
cp ~/dotfiles/dots/.Xdefaults ~/.Xdefaults
# xrdb ~/.Xdefaults
cat ~/dotfiles/.bashrc >> ~/.bashrc
# TODO Find way to install Firefox dotfiles

# Install Vundle and plugins
echo "Installing vundle and vim plugins..."
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
vim +PluginInstall +qall

echo "Script is finished. Exit the chroot, then run 'sudo enter-chroot xinit' and follow the i3 setup instructions. Once that's done, run 'installScriptP2'"
